### ISSUE TITLE
hs6 is converted to integer

### ISSUE THREAD

**Issue by chrmongeau** [SWS-Methodology/faoswsTrade#125]
HS codes are now converted to integers when transforming them to HS6 ([here](https://github.com/SWS-Methodology/faoswsTrade/blob/e88b8052f1fa960b3bef7848dc8a77636d273493/R/adaptTradeDataNames.R#L35) and [here](https://github.com/SWS-Methodology/faoswsTrade/blob/e88b8052f1fa960b3bef7848dc8a77636d273493/R/adaptTradeDataNames.R#L47). E.g.:

```
> glimpse(select(esdata, hs, hs6))
Observations: 979,456
Variables: 2
$ hs  <chr> "01061900", "02032990", "02101219", "02101981", "03079917", "03079917", "03079980", ...
$ hs6 <int> 10619, 20329, 21012, 21019, 30799, 30799, 30799, 40390, 40390, 40390, 40610, 40690, ...
```

Wouldn't it be better to leave hs6 as characters? I see that they are being used in `filterHS6FAOinterest()`, which [converts the codes to integers](https://github.com/SWS-Methodology/faoswsTrade/blob/e88b8052f1fa960b3bef7848dc8a77636d273493/R/filterHS6FAOinterest.R#L15), but I think it would produce the same results if they were characters.

@malexan What's the rationale for the conversion?

**Comment by malexan** [comment]
We store hs as character strings because we need it during aligning of code lengths in the mapping table and raw data set. Otherwise I would prefer to store them as numeric values. Because basically hs code (in our case) is a numeric value.

With hs6 we are sure in length so we don't care about aligning, so why not to store numbers as numbers but not as symbols? (I suspect it is faster, but not on our scale). 

But are there any problems with numeric hs6? I need numeric values during hs6->fcl mapping, but could do conversion on a lower level, if you need characters.

**Comment by chrmongeau** [comment]
> But are there any problems with numeric hs6?

No, I don't think so. I raised the issue because I didn't understand the need for the conversion, but:

> I need numeric values during hs6->fcl mapping

Point taken.

**Comment by malexan** [comment]
@carola-f: 
> Can you explain why you need numeric codes during HS6 > FCL mapping? There are leading 0 in the HS codes, so converting them to numbers instead of
> using characters will re-introduce the problem of changing the codes and altering their length.
 
We don't need to alter length of codes in HS6 mapping table or in trade data, because all codes already have similar length a priori and ready for mapping. 

In actual fact our traditional approach employs similar algorithm. With the difference that HS6 aligning to 6 digits takes place for all reporters and flows simultaneously. I convert[=align to length of 6] all codes in raw trade data and in the mapping table before actual mapping process. So we don't need to save extra data in form of character strings. 

But in traditional approach we align codes for each reporter/flow subgroup individually. So it is easier to do the aligning together with the mapping.

I gave detailed explanation of this HS6 approach and its combination with our traditional approach in issue [Create subroutine to map commodities based on hs6->fcl one-to-one links](https://github.com/SWS-Methodology/faoswsTrade/issues/122#issue-218849212).
