### ISSUE TITLE
Livestock imputation and livestock table

### ISSUE THREAD

**Issue by baldwinkl** [SWS-Methodology/faoswsTrade#159]
Livestock table needs to be incorporated into the trade module, and livestock imputations improved. Right now, the imputations are very out of line with previous series, and can be improved.

![image](https://user-images.githubusercontent.com/31275016/30100620-bfc5fe2a-92e9-11e7-831f-5cd164fc3abe.png)

![image](https://user-images.githubusercontent.com/31275016/30100627-c391a0f4-92e9-11e7-8414-2b049911e568.png)

**Comment by chrmongeau** [comment]
With 286cb2dd the `livestock_weights` table is read and weights are used. This issue should not be considered closed yet because:

- It seems that for some items the weights worsens data compared to previous results.
- The `livestock_weights` table should be a datatable on SWS instead of being harcoded.
- A final decision on how to use the `livestock_weights` table should be taken. It is currently used by applying the weights in the table to the corresponding reporter and for all the flows, but it seems that other uses are possible.

**Comment by chrmongeau** [comment]
Code-side this is closed. See #167.
