### ISSUE TITLE
trade module does not produce output for years before 2009

### ISSUE THREAD

**Issue by bowerth** [SWS-Methodology/faoswsTrade#37]
the execution of the R plugin 'Complete Trade Flow CPC' you have requested has failed.

The plugin was launched over the following datasets:
- completed_tf_cpc_m49 in domain trade

and with the following parameters:
- year = 2008
  - out_coef = 1.5

The plugin started Fri, 5 Aug 2016 11:41:44 +0200 and ended Fri, 5 Aug 2016 12:06:20 +0200 with the following message:

Error message from R: Error: cannot join on columns 'fcl' x 'fcl': index out of bounds

Stacktrace: 
stop(list(message = "cannot join on columns 'fcl' x 'fcl': index out of bounds ", .Call("dplyr_left_join_impl", PACKAGE = "dplyr", x, y, by_x, left_join_impl(x, y, by$x, by$y) left_join.tbl_df(., fclunits, by = "fcl") left_join(., fclunits, by = "fcl")
function_list[[k]](value)
withVisible(function_list[[k]](value))
freduce(value, `_function_list`)
`_fseq`(`_lhs`)
eval(expr, envir, enclos)
eval(quote(`_fseq`(`_lhs`)), env, env)
withVisible(eval(quote(`_fseq`(`_lhs`)), env, env)) esdata %>% left_join(fclunits, by = "fcl")

**Comment by chrmongeau** [comment]
Is this (i.e., expand the hsfclmap2 datatable to years <2009) something @malexan is planned to work on, right?

**Comment by malexan** [comment]
Yep, I suspect.

Do I remember correctly, origins of `hsfclmap2` lay in MDB files with trade notes?

**Comment by sebastian-c** [comment]
Hi Alex! :)

I can't seem to track its history, but I suspect that's the case. For reference the file looks like:

![image](https://cloud.githubusercontent.com/assets/1818581/18987110/6e41c1a6-8700-11e6-8e6c-b47e9e078ca9.png)

Huh... github automatically made an image from the pasted data. Cool, but not selectable.

**Comment by malexan** [comment]
Hi Sebastian! :) 

Right, it is from there. I had an access to the directory with MDB files (`essdata/TradeSys/TradeSys/Countries`) and read them with [R scripts](https://gitlab.com/faoess/hsfclmap/tree/master/data-raw).

I just [took 2009 year](https://gitlab.com/faoess/hsfclmap/blob/master/data-raw/read_from_mdb.R) as starting point, because data in MDBs is not ideal and each additional year requires manual checks of errors, explored during the export.

So next steps are to get the access again, read new (old) MDB files and correct discovered errors (with Team F?).

**Comment by sebastian-c** [comment]
This issue will have to deal with #42 as well to move ahead.

**Comment by chrmongeau** [comment]
`hsfclmap2` is now `hsfclmap3` and #42 is closed.
